### ISSUE TITLE
Couldn't save to cache: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by netxecute** [cryptoprofitswitcher/CryptonightProfitSwitcher#10]
Been running fairly well for several days.. Sometimes it stops mining but I couldn't determine why.

Now I see this error every time it runs, it still runs but thought I would let you know.

Couldn't save to cache: Object reference not set to an instance of an object.

EDIT: Please let me know if you need any further details (OS, software versions, etc.)

**Comment by cryptoprofitswitcher** [comment]
Can you try to delete the _Cache_ folder?

**Comment by netxecute** [comment]
Got rid of error message. Does it just slow it down a bit since it can't use cache?

**Comment by cryptoprofitswitcher** [comment]
No, the cache just exists to get the last data if one API is unreachable.

**Comment by cryptoprofitswitcher** [comment]
I tried to fix the issue that it stops mining in version 4.0.0.
Please try out the latest release and reopen an issue if you still have problems.

**Comment by netxecute** [comment]
I will try once I can download the file. Aws that github uses is down.
