### ISSUE TITLE
Couldn't get current hashrate: Can not convert Null to Double.

### ISSUE THREAD

**Issue by netxecute** [cryptoprofitswitcher/CryptonightProfitSwitcher#11]
Sometimes the watchdog can't get hashrate from the stak api.
When this happens, if a vega drops or whatever, it won't restart.

**Comment by cryptoprofitswitcher** [comment]
This isn't an issue because if you get this message it means that the app couldn't get the current hash rate and it will report by standard 0 as the current hash rate. So the watchdog should work normally.

**Comment by netxecute** [comment]
It didn't seem to be working that way, because a Vega had dropped and also the watchdog number wasn't going up. I failed to document it though. I will see if it replicates.

**Comment by cryptoprofitswitcher** [comment]
Please test out the latest version and reopen an issue if you still have problems.
