### ISSUE TITLE
PrepareScript.bat doesn't launch in between switching coins

### ISSUE THREAD

**Issue by netxecute** [cryptoprofitswitcher/CryptonightProfitSwitcher#17]
My understanding based on your reddit comment was it should.
The coin switch is using 3600 seconds cooldown.

let me know if you need more info

**Comment by cryptoprofitswitcher** [comment]
I made a test and it worked as expected. Maybe you're doing something wrong in your configuration?

**Comment by netxecute** [comment]
What more info do you need?

I've got the exact same preparescript.bat as my resetscript.bat which runs fine when I hit "r"

I've got the reset in the main folder and the prepare in the coins folder.

**Comment by cryptoprofitswitcher** [comment]
Can you try to put the script in the main folder?
The line in the configuration of a coin or NiceHash algorithm should look like:

If in main folder:
`  "PrepareScript": "preparescript.bat",`

If in Coins folder:
`  "PrepareScript": "Coins/preparescript.bat",`

**Comment by netxecute** [comment]
that was it
