### ISSUE TITLE
Bittube not working

### ISSUE THREAD

**Issue by felipe-vvoosh** [cryptoprofitswitcher/CryptonightProfitSwitcher#22]
I keep getting invalid shares with Bittube, is everything ok for you guys?

Thanks

**Comment by felipe-vvoosh** [comment]
Hi @cryptoprofitswitcher, it seems that the new version of Xmr-Stak (2.4.6) now accepts Bittube... Can you update with that here? Because currently it's calling the ipbc which makes impossible to mine Bittube with your solution. Thanks!

**Comment by felipe-vvoosh** [comment]
It will be just a matter of replacing "ipbc" for "bittube" in the currency and compiling again. Thanks.

**Comment by netxecute** [comment]
please also be sure to add the miner rocks api - they are adding bittube

bittube.miner.rocks

**Comment by cryptoprofitswitcher** [comment]
Fixed in 4.5.0
