### ISSUE TITLE
new version, problem.

### ISSUE THREAD

**Issue by DanAisp** [cryptoprofitswitcher/CryptonightProfitSwitcher#30]
Hi, I try to install the new version but I have an error:

`Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.IO.FileSystem, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
Abortado (`core' generado)`

Linux Ubuntu 16.04
driver amd 18.10
kernel 4.15

The previous version works perfectly.
Thanks

**Comment by DanAisp** [comment]
I love this software, I don't have too much money, but if you need a donation, I wish can help. The new version is perfect but the bug does not let me work :(.

**Comment by cryptoprofitswitcher** [comment]
Should be fixed in V. 5.5.0
