### ISSUE TITLE
Option to switch based on coin reward ignoring price

### ISSUE THREAD

**Issue by netxecute** [cryptoprofitswitcher/CryptonightProfitSwitcher#7]
I'd love to basically ignore the btc or usd price and just base the switching on coin reward.
Something like comparing live with the weighted 24hr avg and selecting the coin with the greatest positive variance.

maybe something like this
decimal wavg24 coin reward = (coin.GetExpectedHashrate(settings) * (86400 / lastStats.pool.stats.diffs["wavg24h"])) * reward;

decimal live coin reward = (coin.GetExpectedHashrate(settings) * (86400 / lastStats.network.difficulty)) * reward;

**Comment by cryptoprofitswitcher** [comment]
Good idea, implemented in Release 3.5.0.
