### ISSUE TITLE
run on linux?

### ISSUE THREAD

**Issue by nicolasdanelon** [cryptoprofitswitcher/CryptonightProfitSwitcher#8]
any change to run this on linux? since powershell and dotnetcore are available in ubuntu, it could be usefull to dockerize this

**Comment by cryptoprofitswitcher** [comment]
I added an experimental release for LinuxX64 but it is untested and does not contain Xmr-Stak for Linux.
You can test it out.

**Comment by cryptoprofitswitcher** [comment]
Version 4.0.0 will work with Linux.

**Comment by nicolasdanelon** [comment]
please tell me if you need some feedback with the linux version. I'll test it ASAP!! thanks!

**Comment by nicolasdanelon** [comment]
the XmrStak folder is almost empty. I copy the files in the windows version and beside that I'm seeing this issue:

```
CURRENT STATUS: 
Couldn't get data from: http://127.0.0.1:4000/api.json
Error message: One or more errors occurred. (An error occurred while sending the request.)
Couldn't get current hashrate: One or more errors occurred. (An error occurred while sending the request.)
 Mining:     MoneroOcean at 0H/s Cooldown:   Ready to switch.
 Switching:  MaximizeFiat
 Watchdog:   1 consecutive overshot(s) out of 10 allowed.

 Will refresh automatically in 40 seconds.
```

I'm running ubuntu 18.04 LTS
Linux workstation 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
